print("Hi! I can detect following objects when you show them to me :-) ")

print("\n")

print("person bicycle car motorbike aeroplane bus train truck boat traffic light")
print("\n")
print("fire-hydrant stop-sign parking-meter bench bird cat dog  horse sheep")
print("\n")
print (" horse sheep cow elephant bear zebra giraffe backpack umbrella handbag ")
print("\n")
print(" tie suitcase frisbee skis snowboard sports ball kite skateboard surfboard ")
print("\n")
print(" tennis-racket bottle wine glass cup fork knife spoon bowl banana apple")
print("\n")
print(" sandwich orange broccoli carrot hot dog pizza donut cake chair sofa pottedplant bed diningtable toilet")
print("\n")
print("TV laptop mouse remote keyboard cell phone microwave-oven toaster sink refrigerator book clock vase" )
print("\n")
print(" scissors teddy bear hair drier toothbrush")
